### ISSUE TITLE
Typos in README.md

### ISSUE THREAD

**Issue by TheDarkW3b** [1010varun/urlShortner#2]
There are some typos in README that needs to be fixed and correct navigation/link to contribution.md

**Comment by TheDarkW3b** [comment]
Please don't forget to assign the `iwoc2024` label :)

**Comment by alokvns48** [comment]
I have read the README file and identified the typos , I would like to work on the issue. Please assign this issue to me

**Comment by TheDarkW3b** [comment]
> I have read the README file and identified the typos , I would like to work on the issue. Please assign this issue to me

Can't you see the PR linked to the issue?

**Comment by alokvns48** [comment]
> > I have read the README file and identified the typos , I would like to work on the issue. Please assign this issue to me
> 
> Can't you see the PR linked to the issue? @alokvns48
Sorry! my bad
