### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by AbhineshJha** [1010varun/urlShortner#4]
As this repo has not  the code of conduct file ..
so i wanna work in this issue under IWOC

**Comment by 1010varun** [comment]
@AbhineshJha describe me this issue briefly

**Comment by AbhineshJha** [comment]
sir @1010varun  A CODE_OF_CONDUCT.md file in a GitHub repository outlines expected behavior, unacceptable conduct, reporting guidelines, consequences for violations, and contact information for maintaining a positive and inclusive community. It sets standards for respectful collaboration and provides a mechanism for addressing violations.

**Comment by 1010varun** [comment]
@AbhineshJha, seems interesting assigning it to you
