### ISSUE TITLE
QR Code Generator for URLs

### ISSUE THREAD

**Issue by TanushreeBorase** [1010varun/urlShortner#6]
Description
This project creates a simple web page using HTML, CSS, and JavaScript to generate a QR code for a specified URL.

Checklist
 I have checked the existing issues.
 I follow [Contributing Guidelines]
 I am a IWOC'24 contributor.
 
Code of Conduct
 I agree to follow this project's "[Code of Conduct]

**Comment by TanushreeBorase** [comment]
I would like to work on this @1010varun . Please assign me

**Comment by 1010varun** [comment]
@TanushreeBorase what is the role of the QR code in this project? This project focuses on making URLs smaller so that they can be shared easily, if we generate the QR then what is the benefit of URL shortener

**Comment by TanushreeBorase** [comment]
Thanks for you question. According to me , QR codes will offer an additional layer of accessibility and ease of use. By generating QR codes for the shortened URLs, we provide users with a quick and efficient way to access the information. This can be particularly beneficial in scenarios where scanning a code is more convenient.
